
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - accepted_values:
                values: [1,2]
                quote: false


  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "total order amount by customer"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: dates
    description: "date dimension"
